title = "GABRIEL GONÇALVES"
baseURL = "http://localhost:1313"
languageCode = "en-us"
theme = "anankedit"

DefaultContentLanguage = "pt"
SectionPagesMenu = "main"
Paginate = 25
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Estudante das tecnologias Front-End"
  facebook = ""
  twitter = "https://twitter.com/_gabrielSPEEDY"
  instagram = ""
  youtube = ""
  github = "https://github.com/gabrielbastos13"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/gabriel-goncalves-bastos/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-black"
  featured_image = "/images/workspace.jpeg"
  recent_posts_number = 5
  body_classes = "avenir bg-light-gray"
